version: "3"

services:

    web-mvc:
        image: desenvolvedorio/devstore-web-mvc-ecommerce:latest
        container_name: devstore-web-mvc-ecommerce
        build:
            context: ../src
            dockerfile: ./web/DevStore.WebApp.MVC/Dockerfile
        restart: always            
        environment:
            ASPNETCORE_ENVIRONMENT: Docker
            ASPNETCORE_URLS: "https://+:443;http://+:80"
            ASPNETCORE_Kestrel__Certificates__Default__Password: 9HoGMnb7Lu8NFdHBz4Vq2rtKivzMhmMXhtvuB4TZcLMmbWfFmDQCjJeLURAJ4GYe
            ASPNETCORE_Kestrel__Certificates__Default__Path: /https/devstore.academy-localhost.pfx
            LC_ALL: "en_US.UTF-8"
            LANG: "en_US.UTF-8"
            # Change the two lines above to your culture (ex pt_BR)
        volumes: 
            - ./certs:/https:ro      
        depends_on:
            - api-catalog
            - api-identity
            - api-customers
            - api-bff-checkout
            - generate-pfx
    
    devstore-rabbit:
        image: rabbitmq:3-management
        container_name: devstore-rabbit
        ports:
            - 5672
            - 15672
        environment:
            RABBITMQ_DEFAULT_USER: "devstore"
            RABBITMQ_DEFAULT_PASS: "devstore"


    database-identity:
            image: mcr.microsoft.com/mssql/server:2017-latest
            container_name: devstore-database-identity
            expose:
                - 1433
            environment:
                SA_PASSWORD: "MyDB@123"
                ACCEPT_EULA: "Y"               
            
    api-identity:
        image: desenvolvedorio/devstore-api-identity:latest
        container_name: devstore-api-identity    
        build: 
            context: ../src
            dockerfile: ./services/DevStore.Identity.API/Dockerfile  
        restart: always    
        environment: 
            ASPNETCORE_ENVIRONMENT: Docker
            ASPNETCORE_URLS: https://+:443;http://+:80
            ASPNETCORE_Kestrel__Certificates__Default__Password: 9HoGMnb7Lu8NFdHBz4Vq2rtKivzMhmMXhtvuB4TZcLMmbWfFmDQCjJeLURAJ4GYe
            ASPNETCORE_Kestrel__Certificates__Default__Path: /https/devstore.academy-localhost.pfx
            CUSTOMCONNSTR_DefaultConnection: "Server=database-identity;Database=DSUsers;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
            AppSettings__DatabaseType: SqlServer
        volumes:
            - ./certs:/https:ro
        depends_on:
            - devstore-rabbit
            - database-identity
            - generate-pfx

    database-cart:
            image: mcr.microsoft.com/mssql/server:2017-latest
            container_name: devstore-database-cart
            expose:
                - 1433
            environment:
                SA_PASSWORD: "MyDB@123"
                ACCEPT_EULA: "Y"             

    api-cart:
        image: desenvolvedorio/devstore-api-cart:latest
        container_name: devstore-api-cart
        build: 
            context: ../src
            dockerfile: ./services/DevStore.ShoppingCart.API/Dockerfile      
        restart: always             
        environment: 
            ASPNETCORE_ENVIRONMENT: Docker
            ASPNETCORE_URLS: https://+:443;http://+:80
            ASPNETCORE_Kestrel__Certificates__Default__Password: 9HoGMnb7Lu8NFdHBz4Vq2rtKivzMhmMXhtvuB4TZcLMmbWfFmDQCjJeLURAJ4GYe
            ASPNETCORE_Kestrel__Certificates__Default__Path: /https/devstore.academy-localhost.pfx
            CUSTOMCONNSTR_DefaultConnection: "Server=database-cart;Database=DSShoppingCart;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
            AppSettings__DatabaseType: SqlServer          
        volumes:
            - ./certs:/https:ro
        depends_on:
            - devstore-rabbit
            - api-identity
            - database-cart
            - generate-pfx

    database-catalog:
            image: mcr.microsoft.com/mssql/server:2017-latest
            container_name: devstore-database-catalog
            expose:
                - 1433
            environment:
                SA_PASSWORD: "MyDB@123"
                ACCEPT_EULA: "Y"               

    api-catalog:
        image: desenvolvedorio/devstore-api-catalog:latest
        container_name: devstore-api-catalog
        build: 
            context: ../src
            dockerfile: ./services/DevStore.Catalog.API/Dockerfile
        restart: always 
        environment: 
            ASPNETCORE_ENVIRONMENT: Docker
            ASPNETCORE_URLS: https://+:443;http://+:80
            ASPNETCORE_Kestrel__Certificates__Default__Password: 9HoGMnb7Lu8NFdHBz4Vq2rtKivzMhmMXhtvuB4TZcLMmbWfFmDQCjJeLURAJ4GYe
            ASPNETCORE_Kestrel__Certificates__Default__Path: /https/devstore.academy-localhost.pfx
            CUSTOMCONNSTR_DefaultConnection: "Server=database-catalog;Database=DSCatalog;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
            AppSettings__DatabaseType: SqlServer        
        volumes:
            - ./certs:/https:ro
        depends_on:
            - devstore-rabbit
            - database-catalog
            - generate-pfx

    database-customers:
            image: mcr.microsoft.com/mssql/server:2017-latest
            container_name: devstore-database-customers
            expose:
                - 1433
            environment:
                SA_PASSWORD: "MyDB@123"
                ACCEPT_EULA: "Y"             

    api-customers:
        image: desenvolvedorio/devstore-api-customers:latest
        container_name: devstore-api-customers    
        build: 
            context: ../src
            dockerfile: ./services/DevStore.Customers.API/Dockerfile
        restart: always 
        environment: 
            ASPNETCORE_ENVIRONMENT: Docker
            ASPNETCORE_URLS: https://+:443;http://+:80
            ASPNETCORE_Kestrel__Certificates__Default__Password: 9HoGMnb7Lu8NFdHBz4Vq2rtKivzMhmMXhtvuB4TZcLMmbWfFmDQCjJeLURAJ4GYe
            ASPNETCORE_Kestrel__Certificates__Default__Path: /https/devstore.academy-localhost.pfx
            CUSTOMCONNSTR_DefaultConnection: "Server=database-customers;Database=DSCustomers;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
            AppSettings__DatabaseType: SqlServer                 
        volumes:
            - ./certs:/https:ro
        depends_on:
            - devstore-rabbit
            - api-identity
            - database-customers
            - generate-pfx

    api-bff-checkout:
        image: desenvolvedorio/devstore-api-bff-checkout:latest
        container_name: devstore-api-bff-checkout
        build: 
            context: ../src
            dockerfile: ./api-gateways/DevStore.Bff.Checkout/Dockerfile  
        restart: always 
        environment: 
            ASPNETCORE_ENVIRONMENT: Docker
            ASPNETCORE_URLS: https://+:443;http://+:80
            ASPNETCORE_Kestrel__Certificates__Default__Password: 9HoGMnb7Lu8NFdHBz4Vq2rtKivzMhmMXhtvuB4TZcLMmbWfFmDQCjJeLURAJ4GYe
            ASPNETCORE_Kestrel__Certificates__Default__Path: /https/devstore.academy-localhost.pfx       
        volumes:
            - ./certs:/https:ro
        depends_on:
            - devstore-rabbit
            - api-identity
            - api-cart
            - api-billing
            - api-order
            - generate-pfx
 
    database-billing:
        image: mcr.microsoft.com/mssql/server:2017-latest
        container_name: devstore-database-billing
        expose:
            - 1433
        environment:
            SA_PASSWORD: "MyDB@123"
            ACCEPT_EULA: "Y"


    api-billing:
        image: desenvolvedorio/devstore-api-billing:latest
        container_name: devstore-api-billing    
        build: 
            context: ../src
            dockerfile: ./services/DevStore.Billing.API/Dockerfile
        restart: always    
        environment: 
            ASPNETCORE_ENVIRONMENT: Docker
            ASPNETCORE_URLS: https://+:443;http://+:80
            ASPNETCORE_Kestrel__Certificates__Default__Password: 9HoGMnb7Lu8NFdHBz4Vq2rtKivzMhmMXhtvuB4TZcLMmbWfFmDQCjJeLURAJ4GYe
            ASPNETCORE_Kestrel__Certificates__Default__Path: /https/devstore.academy-localhost.pfx
            CUSTOMCONNSTR_DefaultConnection: "Server=database-billing;Port=5432;Database=DSBilling;User Id=sa;Password=MyDB@123"
            AppSettings__DatabaseType: SqlServer
        volumes:
            - ./certs:/https:ro
        depends_on:
            - devstore-rabbit
            - api-identity
            - api-order
            - database-billing
            - generate-pfx

    database-order:
            image: mcr.microsoft.com/mssql/server:2017-latest
            container_name: devstore-database-order
            expose:
                - 1433
            environment:
                SA_PASSWORD: "MyDB@123"
                ACCEPT_EULA: "Y"               

    api-order:
        image: desenvolvedorio/devstore-api-order:latest
        container_name: devstore-api-order    
        build: 
            context: ../src
            dockerfile: ./services/DevStore.Orders.API/Dockerfile 
        restart: always             
        environment: 
            ASPNETCORE_ENVIRONMENT: Docker
            ASPNETCORE_URLS: https://+:443;http://+:80
            ASPNETCORE_Kestrel__Certificates__Default__Password: 9HoGMnb7Lu8NFdHBz4Vq2rtKivzMhmMXhtvuB4TZcLMmbWfFmDQCjJeLURAJ4GYe
            ASPNETCORE_Kestrel__Certificates__Default__Path: /https/devstore.academy-localhost.pfx
            CUSTOMCONNSTR_DefaultConnection: "Server=database-order;Database=DSOrders;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
            AppSettings__DatabaseType: SqlServer              
        volumes:
            - ./certs:/https:ro
        depends_on:
            - devstore-rabbit
            - database-order
            - api-identity   
            - generate-pfx                 

    seq:
        image: datalust/seq:latest
        expose:
            - 5341
        ports:
            - 5341:80
        environment:
            ACCEPT_EULA: "Y"


    database-status:
        image: mcr.microsoft.com/mssql/server:2017-latest
        container_name: devstore-database-status
        expose:
            - 1433
        environment:
            SA_PASSWORD: "MyDB@123"
            ACCEPT_EULA: "Y"


    web-status:
        image: desenvolvedorio/devstore-web-status:latest
        container_name: devstore-web-status    
        build: 
            context: ../src
            dockerfile: ./web/DevStore.WebApp.Status/Dockerfile
        restart: always    
        environment: 
            ASPNETCORE_ENVIRONMENT: Docker
            ASPNETCORE_URLS: https://+:443;http://+:80
            CUSTOMCONNSTR_DefaultConnection: "Server=database-status;Database=DSOrders;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
            ASPNETCORE_Kestrel__Certificates__Default__Password: 9HoGMnb7Lu8NFdHBz4Vq2rtKivzMhmMXhtvuB4TZcLMmbWfFmDQCjJeLURAJ4GYe
            ASPNETCORE_Kestrel__Certificates__Default__Path: /https/devstore.academy-localhost.pfx
            AppSettings__DatabaseType: SqlServer
            USE_HTTPS_REDIRECTION: "false"
        volumes:
            - ./certs:/https:ro
            - ./certs/devstore.crt:/usr/local/share/ca-certificates/devstore.crt
        depends_on:
            - database-status

    # This service is used to generate the PFX file for gRPC communication
    generate-pfx:
        image: emberstack/openssl
        container_name: generate-pfx
        volumes:
            - ./certs:/https:rw
        command: > 
            sh -c "[ -e "./https/devstore.academy-localhost.pfx" ] && echo File Already exist || (
                   rm -f /https/devstore.academy-localhost.pfx &&
                   openssl genrsa -out devstore.rsa 2048 &&
                   openssl req -sha256 -new -key devstore.rsa -out devstore.csr -subj '/CN=localhost' &&
                   openssl x509 -req -sha256 -days 365 -in devstore.csr -signkey devstore.rsa -out devstore.crt &&
                   openssl pkcs12 -export -out /https/devstore.academy-localhost.pfx -inkey devstore.rsa -in devstore.crt -password pass:9HoGMnb7Lu8NFdHBz4Vq2rtKivzMhmMXhtvuB4TZcLMmbWfFmDQCjJeLURAJ4GYe &&
                   rm devstore.rsa devstore.csr devstore.crt)"

    devstore-server:
        image: nginx
        restart: always 
        volumes:
            - ./nginx/devstore.conf:/etc/nginx/conf.d/default.conf:ro
            - ./nginx/nerdstore-certificate.key:/etc/nginx/nerdstore-certificate.key:ro
            - ./nginx/nerdstore-certificate.pem:/etc/nginx/nerdstore-certificate.pem:ro
        ports:
            - "7500:80"
            - "7501:443"
        depends_on:
            - web-mvc

    
