version: "3"

services:

    rabbitmq:
        image: rabbitmq:3-management
        container_name: devstore-rabbit
        expose:
            - 5672
        environment:
            RABBITMQ_DEFAULT_USER: "devstore"
            RABBITMQ_DEFAULT_PASS: "devstore"  

    generate-pfx:
        image: emberstack/openssl
        container_name: generate-pfx
        volumes:
            - ./certs:/https:rw
        command: > 
            sh -c "[ -e "./https/devstore.academy-localhost.pfx" ] && echo File Already exist || (
                   rm -f /https/devstore.academy-localhost.pfx &&
                   openssl genrsa -out devstore.rsa 2048 &&
                   openssl req -sha256 -new -key devstore.rsa -out devstore.csr -subj '/CN=localhost' &&
                   openssl x509 -req -sha256 -days 365 -in devstore.csr -signkey devstore.rsa -out devstore.crt &&
                   openssl pkcs12 -export -out /https/devstore.academy-localhost.pfx -inkey devstore.rsa -in devstore.crt -password pass:9HoGMnb7Lu8NFdHBz4Vq2rtKivzMhmMXhtvuB4TZcLMmbWfFmDQCjJeLURAJ4GYe &&
                   rm devstore.rsa devstore.csr devstore.crt)"            

    web-mvc:
        image: desenvolvedorio/devstore-web-mvc-ecommerce:latest
        container_name: devstore-web-mvc-ecommerce
        restart: always            
        environment:
            ASPNETCORE_ENVIRONMENT: Docker
            ASPNETCORE_URLS: "https://+:443;http://+:80"
            ASPNETCORE_Kestrel__Certificates__Default__Password: 9HoGMnb7Lu8NFdHBz4Vq2rtKivzMhmMXhtvuB4TZcLMmbWfFmDQCjJeLURAJ4GYe
            ASPNETCORE_Kestrel__Certificates__Default__Path: /https/devstore.academy-localhost.pfx
            LC_ALL: "en_US.UTF-8"
            LANG: "en_US.UTF-8"
            # Change the two lines above to your culture (ex pt_BR)
        volumes: 
            - dpkeys:/var/data_protection_keys/         
        depends_on:
            - api-catalog
            - api-identity
            - api-customers
            - api-bff-checkout
            - generate-pfx

    database-identity:
            image: mcr.microsoft.com/mssql/server:2017-latest
            container_name: devstore-database-identity
            expose:
                - 1433
            environment:
                SA_PASSWORD: "MyDB@123"
                ACCEPT_EULA: "Y"               

    api-identity:
        image: desenvolvedorio/devstore-api-identity:latest
        container_name: devstore-api-identity            
        restart: always    
        environment: 
            ASPNETCORE_ENVIRONMENT: Docker
            ASPNETCORE_URLS: https://+:443;http://+:80
            ASPNETCORE_Kestrel__Certificates__Default__Password: 9HoGMnb7Lu8NFdHBz4Vq2rtKivzMhmMXhtvuB4TZcLMmbWfFmDQCjJeLURAJ4GYe
            ASPNETCORE_Kestrel__Certificates__Default__Path: /https/devstore.academy-localhost.pfx
            CUSTOMCONNSTR_DefaultConnection: "Server=database-identity;Database=DSUsers;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
            AppSettings__DatabaseType: SqlServer            
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - database-identity
            - generate-pfx

    database-cart:
            image: mcr.microsoft.com/mssql/server:2017-latest
            container_name: devstore-database-cart
            expose:
                - 1433
            environment:
                SA_PASSWORD: "MyDB@123"
                ACCEPT_EULA: "Y"                     
            
    api-cart:
        image: desenvolvedorio/devstore-api-cart:latest
        container_name: devstore-api-cart        
        restart: always             
        environment: 
            ASPNETCORE_ENVIRONMENT: Docker
            ASPNETCORE_URLS: https://+:443;http://+:80
            ASPNETCORE_Kestrel__Certificates__Default__Password: 9HoGMnb7Lu8NFdHBz4Vq2rtKivzMhmMXhtvuB4TZcLMmbWfFmDQCjJeLURAJ4GYe
            ASPNETCORE_Kestrel__Certificates__Default__Path: /https/devstore.academy-localhost.pfx
            CUSTOMCONNSTR_DefaultConnection: "Server=database-cart;Database=DSShoppingCart;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
            AppSettings__DatabaseType: SqlServer                 
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identity
            - database-cart
            - generate-pfx

    database-catalog:
            image: mcr.microsoft.com/mssql/server:2017-latest
            container_name: devstore-database-catalog
            expose:
                - 1433
            environment:
                SA_PASSWORD: "MyDB@123"
                ACCEPT_EULA: "Y"                   

    api-catalog:
        image: desenvolvedorio/devstore-api-catalog:latest
        container_name: devstore-api-catalog        
        restart: always 
        environment: 
            ASPNETCORE_ENVIRONMENT: Docker
            ASPNETCORE_URLS: https://+:443;http://+:80
            ASPNETCORE_Kestrel__Certificates__Default__Password: 9HoGMnb7Lu8NFdHBz4Vq2rtKivzMhmMXhtvuB4TZcLMmbWfFmDQCjJeLURAJ4GYe
            ASPNETCORE_Kestrel__Certificates__Default__Path: /https/devstore.academy-localhost.pfx
            CUSTOMCONNSTR_DefaultConnection: "Server=database-catalog;Database=DSCatalog;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
            AppSettings__DatabaseType: SqlServer  
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - database-catalog
            - generate-pfx

    database-customers:
            image: mcr.microsoft.com/mssql/server:2017-latest
            container_name: devstore-database-customers
            expose:
                - 1433
            environment:
                SA_PASSWORD: "MyDB@123"
                ACCEPT_EULA: "Y"                

    api-customers:
        image: desenvolvedorio/devstore-api-customers:latest
        container_name: devstore-api-customers            
        restart: always 
        environment: 
            ASPNETCORE_ENVIRONMENT: Docker
            ASPNETCORE_URLS: https://+:443;http://+:80
            ASPNETCORE_Kestrel__Certificates__Default__Password: 9HoGMnb7Lu8NFdHBz4Vq2rtKivzMhmMXhtvuB4TZcLMmbWfFmDQCjJeLURAJ4GYe
            ASPNETCORE_Kestrel__Certificates__Default__Path: /https/devstore.academy-localhost.pfx
            CUSTOMCONNSTR_DefaultConnection: "Server=database-customers;Database=DSCustomers;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
            AppSettings__DatabaseType: SqlServer                 
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identity
            - database-customers 
            - generate-pfx

    api-bff-checkout:
        image: desenvolvedorio/devstore-api-bff-checkout:latest
        container_name: devstore-api-bff-checkout        
        restart: always 
        environment: 
            ASPNETCORE_ENVIRONMENT: Docker
            ASPNETCORE_URLS: https://+:443;http://+:80
            ASPNETCORE_Kestrel__Certificates__Default__Password: 9HoGMnb7Lu8NFdHBz4Vq2rtKivzMhmMXhtvuB4TZcLMmbWfFmDQCjJeLURAJ4GYe
            ASPNETCORE_Kestrel__Certificates__Default__Path: /https/devstore.academy-localhost.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identity
            - api-cart
            - api-billing
            - api-order
            - generate-pfx

    database-billing:
            image: mcr.microsoft.com/mssql/server:2017-latest
            container_name: devstore-database-billing
            expose:
                - 1433
            environment:
                SA_PASSWORD: "MyDB@123"
                ACCEPT_EULA: "Y"                
            
    api-billing:
        image: desenvolvedorio/devstore-api-billing:latest
        container_name: devstore-api-billing            
        restart: always    
        environment: 
            ASPNETCORE_ENVIRONMENT: Docker
            ASPNETCORE_URLS: https://+:443;http://+:80
            ASPNETCORE_Kestrel__Certificates__Default__Password: 9HoGMnb7Lu8NFdHBz4Vq2rtKivzMhmMXhtvuB4TZcLMmbWfFmDQCjJeLURAJ4GYe
            ASPNETCORE_Kestrel__Certificates__Default__Path: /https/devstore.academy-localhost.pfx
            CUSTOMCONNSTR_DefaultConnection: "Server=database-billing;Database=DSBilling;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
            AppSettings__DatabaseType: SqlServer                      
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identity
            - api-order
            - database-billing
            - generate-pfx

    database-order:
            image: mcr.microsoft.com/mssql/server:2017-latest
            container_name: devstore-database-order
            expose:
                - 1433
            environment:
                SA_PASSWORD: "MyDB@123"
                ACCEPT_EULA: "Y"                 
            
    api-order:
        image: desenvolvedorio/devstore-api-order:latest
        container_name: devstore-api-order            
        restart: always             
        environment: 
            ASPNETCORE_ENVIRONMENT: Docker
            ASPNETCORE_URLS: https://+:443;http://+:80
            ASPNETCORE_Kestrel__Certificates__Default__Password: 9HoGMnb7Lu8NFdHBz4Vq2rtKivzMhmMXhtvuB4TZcLMmbWfFmDQCjJeLURAJ4GYe
            ASPNETCORE_Kestrel__Certificates__Default__Path: /https/devstore.academy-localhost.pfx
            CUSTOMCONNSTR_DefaultConnection: "Server=database-order;Database=DSOrders;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
            AppSettings__DatabaseType: SqlServer               
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - database-order
            - api-identity     
            - generate-pfx               

    seq:
        image: datalust/seq:latest
        ports:
            - 5341:80
        environment:
            ACCEPT_EULA: "Y"
            
    devstore-server:
        image: nginx
        restart: always 
        volumes:
            - ./nginx/devstore.conf:/etc/nginx/conf.d/default.conf:ro
            - ./nginx/nerdstore-certificate.key:/etc/nginx/nerdstore-certificate.key:ro
            - ./nginx/nerdstore-certificate.pem:/etc/nginx/nerdstore-certificate.pem:ro
        ports:
            - "7500:80"
            - "7501:443"
            - "7510:8080"
            - "7511:4443"
        depends_on:
            - web-mvc


volumes:
    dpkeys:     