name: Renovate
on:
  schedule:
    - cron: '0 9,21 * * *'
  push:
    branches:
      - feat/add-renovate
  workflow_dispatch:
      
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.7
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}